services:
  api_db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
      POSTGRES_INITDB_ARGS: "--auth=scram-sha-256"
    ports:
      - "5432:5432"

  api:
    image: api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - api_db
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@api_db:5432/app_db

volumes:
  pgdata:
